"""add is_original and from_url to WorkImage model

Revision ID: 1fc20d4b117a
Revises: 382c66f1bf07
Create Date: 2014-07-13 19:09:14.370866

"""

# revision identifiers, used by Alembic.
revision = '1fc20d4b117a'
down_revision = '382c66f1bf07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_image', sa.Column('from_url', sa.String(length=250), nullable=True))
    op.add_column('work_image', sa.Column('is_original', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_image', 'is_original')
    op.drop_column('work_image', 'from_url')
    ### end Alembic commands ###
