"""Rm fullname.

Revision ID: 56d6939f16e1
Revises: 2469e89395b0
Create Date: 2016-04-19 11:17:03.695519

"""

# revision identifiers, used by Alembic.
revision = '56d6939f16e1'
down_revision = '2469e89395b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('full_name', table_name='collection')
    op.drop_index('full_name_tr', table_name='collection')
    op.drop_column('collection', 'full_name_tr')
    op.drop_column('collection', 'full_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('full_name', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('collection', sa.Column('full_name_tr', mysql.VARCHAR(length=200), nullable=True))
    op.create_index('full_name_tr', 'collection', ['full_name_tr'], unique=True)
    op.create_index('full_name', 'collection', ['full_name'], unique=True)
    ### end Alembic commands ###
