"""rm role from User model

Revision ID: 29414c55ae75
Revises: 47b1bae0e9bc
Create Date: 2014-09-13 12:45:15.262348

"""

# revision identifiers, used by Alembic.
revision = '29414c55ae75'
down_revision = '47b1bae0e9bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    op.drop_column('user', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_super_admin')
    op.drop_column('user', 'is_new')
    op.drop_column('user', 'is_banned')
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
