"""alter constraint for author and dynasty

Revision ID: 382c66f1bf07
Revises: 567cb814b043
Create Date: 2014-07-07 09:45:10.068459

"""

# revision identifiers, used by Alembic.
revision = '382c66f1bf07'
down_revision = '567cb814b043'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_author_abbr', 'author', ['abbr'], unique=False)
    op.drop_constraint(u'abbr', 'author', 'unique')
    op.drop_constraint(u'name', 'dynasty', 'unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'name', 'dynasty', ['name'])
    op.create_unique_constraint(u'abbr', 'author', ['abbr'])
    op.drop_index('ix_author_abbr', table_name='author')
    ### end Alembic commands ###
