"""add mobile title and content to work model

Revision ID: 47b1bae0e9bc
Revises: 5641599ea2a9
Create Date: 2014-08-19 14:43:23.628286

"""

# revision identifiers, used by Alembic.
revision = '47b1bae0e9bc'
down_revision = '5641599ea2a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('mobile_content', sa.Text(), nullable=True))
    op.add_column('work', sa.Column('mobile_title', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'mobile_title')
    op.drop_column('work', 'mobile_content')
    ### end Alembic commands ###
