"""Add highlight_at to Work model.

Revision ID: 50f77e0b9620
Revises: 29414c55ae75
Create Date: 2014-10-12 10:01:41.533677

"""

# revision identifiers, used by Alembic.
revision = '50f77e0b9620'
down_revision = '29414c55ae75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('highlight_at', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'highlight_at')
    ### end Alembic commands ###
