"""rename author quote to quote

Revision ID: 567cb814b043
Revises: None
Create Date: 2014-07-07 08:57:49.903326

"""

# revision identifiers, used by Alembic.
revision = '567cb814b043'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('author_quote', 'quote')
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('work', 'highlight',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('work', 'layout',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('work', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('work_image', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('quote', 'author_quote')
    op.alter_column('work', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('work', 'layout',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('work', 'highlight',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
